
import java.awt.Color;
import java.sql.*;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class Edit_Expense extends javax.swing.JFrame {
            Connection connect = null;
        Statement stmt=null;
    session s= new session();
    
     
    public Edit_Expense() {
        initComponents();
         connect = connectDB.connDB(); 
        getContentPane().setBackground(Color.white);
        this.getID();
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        category = new javax.swing.JLabel();
        payment = new javax.swing.JLabel();
        IncomeExpense = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField("");
        payee = new javax.swing.JTextField("");
        catselect = new javax.swing.JComboBox<>();
        method = new javax.swing.JComboBox<>();
        tag = new javax.swing.JTextField("");
        cheque = new javax.swing.JTextField("");
        jScrollPane1 = new javax.swing.JScrollPane();
        desc = new javax.swing.JTextArea();
        Add = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        subcatselect = new javax.swing.JComboBox<>();
        subcat = new javax.swing.JLabel();
        payment1 = new javax.swing.JLabel();
        status = new javax.swing.JComboBox<>();
        eid = new javax.swing.JComboBox<>();
        payment2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Expense Manager");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel2.setText("Amount");

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel3.setText("Payee");

        category.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        category.setText("Category");

        payment.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        payment.setText("Payment Method");

        IncomeExpense.setBackground(new java.awt.Color(204, 255, 204));
        IncomeExpense.setSelected(true);
        IncomeExpense.setText("Expense");
        IncomeExpense.setActionCommand("Income");
        IncomeExpense.setBorder(null);
        IncomeExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncomeExpenseActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel7.setText("Ref/Cheque No:");

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel9.setText("Description");

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel8.setText("Tag");

        amount.setToolTipText("");
        amount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        amount.setName(""); // NOI18N
        amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountActionPerformed(evt);
            }
        });

        payee.setToolTipText("");
        payee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        payee.setName(""); // NOI18N
        payee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payeeActionPerformed(evt);
            }
        });

        catselect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Personal", "Travel", "Food", "Automobile", "Entertainment", "Family", "Health Care", "Home Office", "Household", "Insurance", "Loans", "Tax", "Utilities", "Vacation", "Other" }));
        catselect.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                catselectItemStateChanged(evt);
            }
        });
        catselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catselectActionPerformed(evt);
            }
        });

        method.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Cheque", "Credit Card", "Debit" }));

        tag.setToolTipText("");
        tag.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tag.setName(""); // NOI18N
        tag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tagActionPerformed(evt);
            }
        });

        cheque.setToolTipText("");
        cheque.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cheque.setName(""); // NOI18N
        cheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chequeActionPerformed(evt);
            }
        });

        desc.setColumns(20);
        desc.setRows(5);
        desc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(desc);

        Add.setBackground(new java.awt.Color(204, 255, 204));
        Add.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Add.setText("Finish");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(204, 255, 204));
        jButton7.setText("Back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        subcatselect.setMaximumRowCount(15);
        subcatselect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clothing", "Donation", "Gift", "Personal Care", "Other" }));
        subcatselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subcatselectActionPerformed(evt);
            }
        });

        subcat.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        subcat.setForeground(new java.awt.Color(0, 51, 0));
        subcat.setText("Sub-Category");

        payment1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        payment1.setText("Status");

        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cleared", "Uncleared", "Reconciled", "Void" }));

        eid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Cheque", "Credit Card", "Debit" }));
        eid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                eidItemStateChanged(evt);
            }
        });

        payment2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        payment2.setText("    ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(payment))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cheque, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(method, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(catselect, 0, 120, Short.MAX_VALUE))
                                        .addGap(74, 74, 74)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(payment1)
                                            .addComponent(subcat, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(subcatselect, 0, 139, Short.MAX_VALUE)
                                    .addComponent(status, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(51, 51, 51)
                        .addComponent(tag, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IncomeExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(amount, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                .addComponent(payee))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(203, 203, 203)
                                .addComponent(payment2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eid, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(84, 84, 84))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(345, 345, 345))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {category, jLabel2, jLabel3, jLabel7, jLabel8, jLabel9, payment});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IncomeExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(payee, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(payment2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(catselect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subcat, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subcatselect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(payment, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(method, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(payment1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cheque, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tag, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {amount, payee});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getID()
    {
        try {                              
                    String sql = "select * from expense_report where user = \'"+s.id+"\' order by Date desc ";
                    stmt = connect.createStatement();
                    eid.removeAllItems(); 
                    ResultSet rse=stmt.executeQuery(sql);
                    while (rse.next()) {  
                                        int ide = rse.getInt("ID");
                                          String ides = Integer.toString(ide);
                                         eid.addItem(ides);             
                                                                     }
        } catch (SQLException e) {
                                                        JOptionPane.showMessageDialog(null, e);
                                                    }
   
    }
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        Summary e = new Summary();
        this.setVisible(false);
        e.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        int type;           
        if (IncomeExpense.isSelected())
                   {
                        type  = 1; 
                   }
                   else
        {
            type = 0;
        }
                  String ides = eid.getSelectedItem().toString();
                   Calendar cal = dt.getCalendar();
                   SimpleDateFormat format1 = new SimpleDateFormat("yyyy-MM-dd");
                   String d = format1.format(cal.getTime());
                   String amt = amount.getText();
                   String paye=payee.getText();
                   String cat = catselect.getSelectedItem().toString();
                   String subc = subcatselect.getSelectedItem().toString();
                   String paym  = method.getSelectedItem().toString();
                   String ref = cheque.getText();
                   String descrp = desc.getText();
                   String tg = tag.getText();
                   String sts = status.getSelectedItem().toString();
                     
                       try {
String sql = "update expense_report set user = \'"+s.id+"\' , Type = \'"+type+"\' , Amount = \'"+amt+"\' , Category = \'"+cat+"\' , SubCategory = \'"+subc+"\' , PaymentMethod = \'"+paym+"\', Description = \'"+descrp+"\' , Payee = \'"+paye+"\' , Status = \'"+sts+"\', RefNumber = \'"+ref+"\', Tag = \'"+tg+"\' , Date = \'"+d+"\' WHERE ID = \'"+ides+"\' ";
                                                                                                                                                                                                                                                                                        
stmt = connect.createStatement();

stmt.executeUpdate(sql);

JOptionPane.showMessageDialog(null, " Updated Successfully !");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }        

                            Main_page l = new Main_page();
                            this.setVisible(false);
                            l.setVisible(true);  
    }//GEN-LAST:event_AddActionPerformed

    private void chequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chequeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chequeActionPerformed

    private void tagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tagActionPerformed

    private void catselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catselectActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_catselectActionPerformed

    private void payeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payeeActionPerformed

    private void amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountActionPerformed

    private void IncomeExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncomeExpenseActionPerformed

        if(IncomeExpense.isSelected())
        IncomeExpense.setText("Expense");
else 
        IncomeExpense.setText("Income");
    }//GEN-LAST:event_IncomeExpenseActionPerformed

    private void subcatselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subcatselectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subcatselectActionPerformed

    private void catselectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_catselectItemStateChanged
if (java.awt.event.ItemEvent.SELECTED == evt.getStateChange()) {

        String src = evt.getItem().toString();
        subcatselect.removeAllItems();
        if(src.equals("Automobile"))
        {
            subcatselect.addItem("Road Service");
            subcatselect.addItem("Fuel");
            subcatselect.addItem("Insurance");
            subcatselect.addItem("Lease");
            subcatselect.addItem("Maintenance");
            subcatselect.addItem("Mileage");
            subcatselect.addItem("Registration");
            subcatselect.addItem("Other");
        }
        
        else if(src.equals("Entertainment"))
        {
            subcatselect.addItem("Concert");
            subcatselect.addItem("Movies");
            subcatselect.addItem("Party");
            subcatselect.addItem("Sports");
            subcatselect.addItem("Other");
        }
        
        else if(src.equals("Family"))
        {
            subcatselect.addItem("Child Care");
            subcatselect.addItem("Child Education");
            subcatselect.addItem("Toy");
            subcatselect.addItem("Other");
        }
        
        else if(src.equals("Food"))
        {
            subcatselect.addItem("Groceries");
            subcatselect.addItem("Restaurant");
            subcatselect.addItem("Snack");
            subcatselect.addItem("Other");
        }
        
        else if(src.equals("Health Care"))
        {
            subcatselect.addItem("Dental");
            subcatselect.addItem("Eye Care");
            subcatselect.addItem("Insurance");
            subcatselect.addItem("Medical");
            subcatselect.addItem("Nutrition");
            subcatselect.addItem("Prescription");
            subcatselect.addItem("Other");
        }
        
        else if(src.equals("Home Office"))
        {
            subcatselect.addItem("Computer");
            subcatselect.addItem("Electronics");
            subcatselect.addItem("Furniture");
            subcatselect.addItem("Stationary");
            subcatselect.addItem("Office Supply");
            subcatselect.addItem("Other");
        }
        
        else if(src.equals("Household"))
        {
            subcatselect.addItem("Appliances");
            subcatselect.addItem("Consumables");
            subcatselect.addItem("Postage");
            subcatselect.addItem("Rent");
            subcatselect.addItem("Home Maintenance");
            subcatselect.addItem("Home Owner Fees");
            subcatselect.addItem("Household Tools");
            subcatselect.addItem("Miscellaneous HOusehols Items");
            subcatselect.addItem("Other");
        }
        
        else if(src.equals("Insurance"))
        {
            subcatselect.addItem("Auto");
            subcatselect.addItem("Health");
            subcatselect.addItem("Home");
            subcatselect.addItem("Life");
            subcatselect.addItem("Other");
        }
        
        else if(src.equals("Loans"))
        {
            subcatselect.addItem("Mortgage");
            subcatselect.addItem("Auto");
            subcatselect.addItem("Home Equity");
            subcatselect.addItem("Student");
            subcatselect.addItem("Other");
        }
        
        else if(src.equals("Personal"))
        {
            subcatselect.addItem("Clothing");
            subcatselect.addItem("Donation");
            subcatselect.addItem("Gift");
            subcatselect.addItem("Personal Care");
            subcatselect.addItem("Other");
        }
        
        else if(src.equals("Tax"))
        {
            subcatselect.addItem("Property");
            subcatselect.addItem("Income ");
            subcatselect.addItem("Other");
        }
        
        else if(src.equals("Travel"))
        {
            subcatselect.addItem("Airplane");
            subcatselect.addItem("Car Rental");
            subcatselect.addItem("Food");
            subcatselect.addItem("Hotel");
            subcatselect.addItem("Taxi");
            subcatselect.addItem("Misc.");
            subcatselect.addItem("Other Transportation");
            subcatselect.addItem("Other");
        }
        
        else if(src.equals("Utilities"))
        {
            subcatselect.addItem("Cable TV");
            subcatselect.addItem("ELectric");
            subcatselect.addItem("Garbage");
            subcatselect.addItem("Gas");
            subcatselect.addItem("Internet");
            subcatselect.addItem("Telephone");
            subcatselect.addItem("Water");
            subcatselect.addItem("Other");
        }
        
        else if(src.equals("Vacation"))
        {
            subcatselect.addItem("Hotel");
            subcatselect.addItem("Airplane");
            subcatselect.addItem("Car Rental");
            subcatselect.addItem("Food");
            subcatselect.addItem("Taxi");
            subcatselect.addItem("Misc.");
            subcatselect.addItem("Other Transportation");
            subcatselect.addItem("Other");        }
        
        else if(src.equals("Other"))
        {
            subcatselect.addItem("Other");
        }
            








    }        // TODO add your handling code here:
    }//GEN-LAST:event_catselectItemStateChanged

    private void eidItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_eidItemStateChanged
            String src = evt.getItem().toString();
 try {                              
                    String sql = "select * from expense_report where user = \'"+s.id+"\' AND ID =\'"+src+"\'  ";
                    stmt = connect.createStatement();
                                            
                    ResultSet rse=stmt.executeQuery(sql);
                    if (rse.next()) 
                    {  
                                        java.util.Date d = rse.getDate("Date");
                                        dt.setDate(d);
                                          int t = rse.getInt("Type");
                                            
                                            if(t==0)
                                            {
                                                 IncomeExpense.setSelected(false); 
                                            }
                                            else
                                            {
                                              IncomeExpense.setSelected(true);  
                                            }
                                            if(IncomeExpense.isSelected())
        IncomeExpense.setText("Expense");
else 
        IncomeExpense.setText("Income");
                                            int amt = rse.getInt("Amount");
                                            
                                            String amounts = Integer.toString(amt);
                                            String payees = rse.getString("Payee");
                                            String cats = rse.getString("Category");
                                            String subcats = rse.getString("SubCategory");
                                            String paymets = rse.getString("PaymentMethod");
                                            String statuss = rse.getString("Status");
                                            String ref = rse.getString("RefNumber");
                                            String des = rse.getString("Description");
                                            String tags = rse.getString("Tag");
                                                                                  
                                            amount.setText(amounts);
                                            payee.setText(payees);
                                            catselect.setSelectedItem(cats);
                                            subcatselect.setSelectedItem(subcats);
                                            method.setSelectedItem(paymets);
                                            status.setSelectedItem(statuss);
                                            cheque.setText(ref);
                                            desc.setText(des);
                                            tag.setText(tags);
                                            
                    }
        } catch (SQLException e) {
                                                        JOptionPane.showMessageDialog(null, e);
                                                    }
    
    }//GEN-LAST:event_eidItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Expense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Expense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Expense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Expense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit_Expense().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JToggleButton IncomeExpense;
    private javax.swing.JTextField amount;
    private javax.swing.JLabel category;
    private javax.swing.JComboBox<String> catselect;
    private javax.swing.JTextField cheque;
    private javax.swing.JTextArea desc;
    private javax.swing.JComboBox<String> eid;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> method;
    private javax.swing.JTextField payee;
    private javax.swing.JLabel payment;
    private javax.swing.JLabel payment1;
    private javax.swing.JLabel payment2;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JLabel subcat;
    private javax.swing.JComboBox<String> subcatselect;
    private javax.swing.JTextField tag;
    // End of variables declaration//GEN-END:variables
}
