
import java.awt.Color;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vaibhav
 */
public class Main_page extends javax.swing.JFrame {
        
        Connection connect = null;
        Statement stmt=null;
        session s = new session();
        
        
        /**
    /**
     * Creates new form pageA
     */
    public Main_page() {
        initComponents();
        
        
        
        
       if (s.isSet())
       {
          Login_button.setText("Logout");
            Signup_button.setText(s.name);
            Add_Expense.setEnabled(true);
            summary.setEnabled(true);
        }
       Color c = new Color(204,255,204);
        getContentPane().setBackground(c);
        connect = connectDB.connDB();  
     this.setBalance();
    this.setDates();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        summary = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        jLabel23 = new javax.swing.JLabel();
        monthIncome = new javax.swing.JLabel();
        monthBalance = new javax.swing.JLabel();
        currentMonth = new javax.swing.JLabel();
        monthExpense = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        current_Balance = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jLabel18 = new javax.swing.JLabel();
        weekIncome = new javax.swing.JLabel();
        weekBalance = new javax.swing.JLabel();
        currentDay = new javax.swing.JLabel();
        weekExpense = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        Login_button = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel8 = new javax.swing.JLabel();
        todayIncome = new javax.swing.JLabel();
        todayBalance = new javax.swing.JLabel();
        currentDate = new javax.swing.JLabel();
        todayExpense = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jLayeredPane7 = new javax.swing.JLayeredPane();
        jLabel33 = new javax.swing.JLabel();
        yearIncome = new javax.swing.JLabel();
        yearBalance = new javax.swing.JLabel();
        currentYear = new javax.swing.JLabel();
        yearExpense = new javax.swing.JLabel();
        jButton22 = new javax.swing.JButton();
        Signup_button = new javax.swing.JButton();
        Add_Expense = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Expense Manager");
        setBackground(new java.awt.Color(204, 255, 204));
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        summary.setBackground(new java.awt.Color(255, 255, 255));
        summary.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        summary.setForeground(new java.awt.Color(0, 102, 51));
        summary.setText("Summary");
        summary.setBorderPainted(false);
        summary.setContentAreaFilled(false);
        summary.setEnabled(false);
        summary.setMaximumSize(new java.awt.Dimension(50, 50));
        summary.setMinimumSize(new java.awt.Dimension(20, 20));
        summary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summaryActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel1.setText("Income");

        jLayeredPane5.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLayeredPane5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel23.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel23.setText("This month");

        monthIncome.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        monthIncome.setText("0.00");

        monthBalance.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        monthBalance.setText("0.00");

        currentMonth.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        currentMonth.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentMonth.setText("Date current");
        currentMonth.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        currentMonth.setPreferredSize(new java.awt.Dimension(100, 15));

        monthExpense.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        monthExpense.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        monthExpense.setText("0.00");
        monthExpense.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        monthExpense.setPreferredSize(new java.awt.Dimension(100, 15));

        jButton20.setBackground(new java.awt.Color(255, 255, 255));
        jButton20.setFont(new java.awt.Font("Tempus Sans ITC", 1, 10)); // NOI18N
        jButton20.setForeground(new java.awt.Color(0, 102, 51));
        jButton20.setText("Activity");
        jButton20.setBorderPainted(false);
        jButton20.setContentAreaFilled(false);
        jButton20.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton20.setMinimumSize(new java.awt.Dimension(20, 20));
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jLayeredPane5.setLayer(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(monthIncome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(monthBalance, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(currentMonth, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(monthExpense, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(jButton20, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane5Layout = new javax.swing.GroupLayout(jLayeredPane5);
        jLayeredPane5.setLayout(jLayeredPane5Layout);
        jLayeredPane5Layout.setHorizontalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane5Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel23))
                    .addGroup(jLayeredPane5Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(monthIncome)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(monthExpense, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currentMonth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane5Layout.createSequentialGroup()
                        .addComponent(monthBalance)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane5Layout.createSequentialGroup()
                        .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jLayeredPane5Layout.setVerticalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(currentMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(monthIncome)
                    .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(monthBalance)
                        .addComponent(monthExpense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel2.setText("Expense");

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel3.setText("Balance");

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLayeredPane1.setToolTipText("");

        current_Balance.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        current_Balance.setText("0.00");

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel4.setText("Current Balance ");

        jLayeredPane1.setLayer(current_Balance, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(current_Balance)
                .addGap(45, 45, 45))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(current_Balance))
                .addGap(20, 20, 20))
        );

        jLayeredPane4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLayeredPane4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel18.setText("This Week");

        weekIncome.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        weekIncome.setText("0.00");

        weekBalance.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        weekBalance.setText("0.00");

        currentDay.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        currentDay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentDay.setText("Date current");
        currentDay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        currentDay.setPreferredSize(new java.awt.Dimension(100, 15));

        weekExpense.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        weekExpense.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        weekExpense.setText("0.00");
        weekExpense.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        weekExpense.setPreferredSize(new java.awt.Dimension(100, 15));

        jButton19.setBackground(new java.awt.Color(255, 255, 255));
        jButton19.setFont(new java.awt.Font("Tempus Sans ITC", 1, 10)); // NOI18N
        jButton19.setForeground(new java.awt.Color(0, 102, 51));
        jButton19.setText("Activity");
        jButton19.setBorderPainted(false);
        jButton19.setContentAreaFilled(false);
        jButton19.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton19.setMinimumSize(new java.awt.Dimension(20, 20));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jLayeredPane4.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(weekIncome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(weekBalance, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(currentDay, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(weekExpense, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jButton19, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel18))
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(weekIncome)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(weekExpense, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currentDay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane4Layout.createSequentialGroup()
                        .addComponent(weekBalance)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane4Layout.createSequentialGroup()
                        .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(currentDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(weekIncome)
                    .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(weekBalance)
                        .addComponent(weekExpense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );

        Login_button.setBackground(new java.awt.Color(255, 255, 255));
        Login_button.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        Login_button.setForeground(new java.awt.Color(0, 102, 51));
        Login_button.setText("Login");
        Login_button.setBorderPainted(false);
        Login_button.setContentAreaFilled(false);
        Login_button.setMaximumSize(new java.awt.Dimension(50, 50));
        Login_button.setMinimumSize(new java.awt.Dimension(20, 20));
        Login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_buttonActionPerformed(evt);
            }
        });

        jLayeredPane2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLayeredPane2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel8.setText("Today");

        todayIncome.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        todayIncome.setText("0.00");

        todayBalance.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        todayBalance.setText("0.00");

        currentDate.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        currentDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentDate.setText("Date current");
        currentDate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        currentDate.setPreferredSize(new java.awt.Dimension(100, 15));

        todayExpense.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        todayExpense.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        todayExpense.setText("0.00");
        todayExpense.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        todayExpense.setPreferredSize(new java.awt.Dimension(100, 15));

        jButton14.setBackground(new java.awt.Color(255, 255, 255));
        jButton14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 10)); // NOI18N
        jButton14.setForeground(new java.awt.Color(0, 102, 51));
        jButton14.setText("Activity");
        jButton14.setBorderPainted(false);
        jButton14.setContentAreaFilled(false);
        jButton14.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton14.setMinimumSize(new java.awt.Dimension(20, 20));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(todayIncome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(todayBalance, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(currentDate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(todayExpense, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jButton14, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel8))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(todayIncome)))
                .addGap(221, 221, 221)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(todayExpense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(todayBalance)
                        .addGap(101, 101, 101))))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(currentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(todayIncome)
                    .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(todayBalance)
                        .addComponent(todayExpense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );

        jLayeredPane7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLayeredPane7.setForeground(new java.awt.Color(255, 255, 255));

        jLabel33.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel33.setText("This Year");

        yearIncome.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        yearIncome.setText("0.00");

        yearBalance.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        yearBalance.setText("0.00");

        currentYear.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        currentYear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentYear.setText("Date current");
        currentYear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        currentYear.setPreferredSize(new java.awt.Dimension(100, 15));

        yearExpense.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        yearExpense.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yearExpense.setText("0.00");
        yearExpense.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        yearExpense.setPreferredSize(new java.awt.Dimension(100, 15));

        jButton22.setBackground(new java.awt.Color(255, 255, 255));
        jButton22.setFont(new java.awt.Font("Tempus Sans ITC", 1, 10)); // NOI18N
        jButton22.setForeground(new java.awt.Color(0, 102, 51));
        jButton22.setText("Activity");
        jButton22.setBorderPainted(false);
        jButton22.setContentAreaFilled(false);
        jButton22.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton22.setMinimumSize(new java.awt.Dimension(20, 20));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jLayeredPane7.setLayer(jLabel33, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane7.setLayer(yearIncome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane7.setLayer(yearBalance, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane7.setLayer(currentYear, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane7.setLayer(yearExpense, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane7.setLayer(jButton22, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane7Layout = new javax.swing.GroupLayout(jLayeredPane7);
        jLayeredPane7.setLayout(jLayeredPane7Layout);
        jLayeredPane7Layout.setHorizontalGroup(
            jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane7Layout.createSequentialGroup()
                .addGroup(jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane7Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel33))
                    .addGroup(jLayeredPane7Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(yearIncome)))
                .addGroup(jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                        .addComponent(yearExpense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(217, 217, 217))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(currentYear, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane7Layout.createSequentialGroup()
                        .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane7Layout.createSequentialGroup()
                        .addComponent(yearBalance)
                        .addGap(101, 101, 101))))
        );
        jLayeredPane7Layout.setVerticalGroup(
            jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(currentYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yearIncome)
                    .addGroup(jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(yearBalance)
                        .addComponent(yearExpense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );

        Signup_button.setBackground(new java.awt.Color(255, 255, 255));
        Signup_button.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        Signup_button.setForeground(new java.awt.Color(0, 102, 51));
        Signup_button.setText("Sign up");
        Signup_button.setBorderPainted(false);
        Signup_button.setContentAreaFilled(false);
        Signup_button.setMaximumSize(new java.awt.Dimension(50, 50));
        Signup_button.setMinimumSize(new java.awt.Dimension(20, 20));
        Signup_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Signup_buttonActionPerformed(evt);
            }
        });

        Add_Expense.setBackground(new java.awt.Color(204, 255, 204));
        Add_Expense.setText("Add Expense");
        Add_Expense.setEnabled(false);
        Add_Expense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_ExpenseActionPerformed(evt);
            }
        });

        jButton18.setBackground(new java.awt.Color(255, 255, 255));
        jButton18.setFont(new java.awt.Font("Tempus Sans ITC", 1, 26)); // NOI18N
        jButton18.setText("Personal Expense");
        jButton18.setBorderPainted(false);
        jButton18.setContentAreaFilled(false);
        jButton18.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton18.setMinimumSize(new java.awt.Dimension(20, 20));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLayeredPane2)
                        .addComponent(jLayeredPane1)
                        .addComponent(jLayeredPane4)
                        .addComponent(jLayeredPane5)
                        .addComponent(jLayeredPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(242, 242, 242)
                        .addComponent(jLabel3)
                        .addGap(93, 93, 93)))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Add_Expense)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(summary, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(139, 139, 139)))))
                .addComponent(Login_button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Signup_button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Login_button, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Signup_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Add_Expense))
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(summary, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addComponent(jLabel1))
                .addGap(11, 11, 11)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void setDates()
    {
        java.util.Date d = Calendar.getInstance().getTime();
        Calendar week = Calendar.getInstance(); 
        week.add(Calendar.DAY_OF_MONTH, -7);
        java.util.Date wd = week.getTime();
        
        Calendar month = Calendar.getInstance(); 
        month.set(Calendar.DAY_OF_MONTH, 1);
        java.util.Date md = month.getTime();
        
        Calendar year = Calendar.getInstance(); 
        year.set(Calendar.DAY_OF_YEAR, 1);
        java.util.Date yd = year.getTime();
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd - MM - YYYY");
        SimpleDateFormat sdfd = new SimpleDateFormat("dd - MM");
        String curDate = sdf.format(d);
        String curWeeke = sdfd.format(d);
        String curWeeks = sdfd.format(wd);
        String curMonths = sdfd.format(md);
        String curMonthe = sdfd.format(d);
        String curYears = sdf.format(yd);
        String curYeare= sdf.format(d);
        currentDate.setText(curDate);
        currentDay.setText(curWeeks + "  to  " +curWeeke );
        currentMonth.setText(curMonths + "  to  " + curMonthe );
        currentYear.setText(curYears + "  to  " + curYeare);

    }
    
    private void setBalance()
    {
                                        int totalIncome =0;
                                        int tIncome =0;
                                        int tExpense =0;
                                        int wIncome =0;
                                        int wExpense =0;
                                        int mIncome =0;
                                        int mExpense =0;
                                        int yIncome =0;
                                        int yExpense =0;
                                        int tbalance = 0;
                                        int wbalance = 0;
                                        int mbalance = 0;
                                        int ybalance = 0;
                                        int totalExpense = 0;  
                                        int totalBalance = 0;
        
        try {                              
                    String sqle = "select SUM(Amount) from expense_report where user = \'"+s.id+"\' AND  Type = 1 ";
                    String sqli = "select SUM(Amount) from expense_report where user = \'"+s.id+"\' AND  Type = 0 ";
                    String sqlti = "select SUM(Amount) from expense_report where user = \'"+s.id+"\' AND  Type = 0 AND Date = curdate()";
                    String sqlte = "select SUM(Amount) from expense_report where user = \'"+s.id+"\' AND  Type = 1 AND Date = curdate()";
                    String sqlwi = "select SUM(Amount) from expense_report where user = \'"+s.id+"\' AND  Type = 0 AND Date between date_sub(now(),INTERVAL DAYOFWEEK(NOW())-2 DAY) and now()";
                    String sqlwe = "select SUM(Amount) from expense_report where user = \'"+s.id+"\' AND  Type = 1 AND Date between date_sub(now(),INTERVAL DAYOFWEEK(NOW())-2 DAY) and now()";
                    String sqlme = "select SUM(Amount) from expense_report where user = \'"+s.id+"\' AND  Type = 1 AND Date between date_sub(now(),INTERVAL DAYOFMONTH(NOW())-1 DAY) and now()";
                    String sqlmi = "select SUM(Amount) from expense_report where user = \'"+s.id+"\' AND  Type = 0 AND Date between date_sub(now(),INTERVAL DAYOFMONTH(NOW())-1 DAY) and now()";
                    String sqlye = "select SUM(Amount) from expense_report where user = \'"+s.id+"\' AND  Type = 1 AND Date between date_sub(now(),INTERVAL DAYOFYEAR(NOW())-1 DAY) and now()";
                    String sqlyi = "select SUM(Amount) from expense_report where user = \'"+s.id+"\' AND  Type = 0 AND Date between date_sub(now(),INTERVAL DAYOFYEAR(NOW())-1 DAY) and now()";
                                                                    
                    stmt = connect.createStatement();
                                            ResultSet rse=stmt.executeQuery(sqle);
                                            
				while(rse.next())
				{
                                    int e = rse.getInt(1);
                                     totalExpense += e;
                                }
                                ResultSet rsi=stmt.executeQuery(sqli);
                                
                                while(rsi.next())
				{
                                     int i = rsi.getInt(1);
                                     totalIncome += i;
                                }
                                
                                ResultSet rsti=stmt.executeQuery(sqlti);
                                
                                while(rsti.next())
				{
                                     int ti = rsti.getInt(1);
                                     tIncome += ti;
                                }
                                
                                ResultSet rste=stmt.executeQuery(sqlte);
                                
                                while(rste.next())
				{
                                     int te = rste.getInt(1);
                                     tExpense += te;
                                }
                                
                                ResultSet rswi=stmt.executeQuery(sqlwi);
                                
                                while(rswi.next())
				{
                                     int wi = rswi.getInt(1);
                                     wIncome += wi;
                                }
                                
                                ResultSet rswe=stmt.executeQuery(sqlwe);
                                
                                while(rswe.next())
				{
                                     int we = rswe.getInt(1);
                                     wExpense += we;
                                }
                                
                                ResultSet rsmi=stmt.executeQuery(sqlmi);
                                
                                while(rsmi.next())
				{
                                     int mi = rsmi.getInt(1);
                                     mIncome += mi;
                                }
                                
                                ResultSet rsme=stmt.executeQuery(sqlme);
                                
                                while(rsme.next())
				{
                                     int me = rsme.getInt(1);
                                     mExpense += me;
                                }
                                
                                ResultSet rsyi=stmt.executeQuery(sqlyi);
                                
                                while(rsyi.next())
				{
                                     int yi = rsyi.getInt(1);
                                     yIncome += yi;
                                }
                                
                                ResultSet rsye=stmt.executeQuery(sqlye);
                                
                                while(rsye.next())
				{
                                     int ye = rsye.getInt(1);
                                     yExpense += ye;
                                }
                                              } catch (SQLException e) {
                                                        JOptionPane.showMessageDialog(null, e);
                                                    }
        
    
    totalBalance = totalIncome- totalExpense;
    tbalance = tIncome- tExpense;
    wbalance = wIncome- wExpense;
    mbalance = mIncome- mExpense;
    ybalance = yIncome- yExpense;
    
    current_Balance.setText(Integer.toString(totalBalance));
    
    todayIncome.setText(Integer.toString(tIncome));
    todayExpense.setText(Integer.toString(tExpense));
    todayBalance.setText(Integer.toString(tbalance));
    
    weekIncome.setText(Integer.toString(wIncome));
    weekExpense.setText(Integer.toString(wExpense));
    weekBalance.setText(Integer.toString(wbalance));
    
    monthIncome.setText(Integer.toString(mIncome));
    monthExpense.setText(Integer.toString(mExpense));
    monthBalance.setText(Integer.toString(mbalance));
    
    yearIncome.setText(Integer.toString(yIncome));
    yearExpense.setText(Integer.toString(yExpense));
    yearBalance.setText(Integer.toString(ybalance));
    
    }
    private void summaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summaryActionPerformed
        Summary s= new Summary();
        this.setVisible(false);
        s.setVisible(true);
    }//GEN-LAST:event_summaryActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void Login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_buttonActionPerformed
       if(s.isSet())
        {
            s.unSet();
            connect = connectDB.connDB();  
            JOptionPane.showMessageDialog(null, "Logged out Successfully");
            Login_button.setText("Login");
            Signup_button.setText("Sign Up");
            Add_Expense.setEnabled(false);
            summary.setEnabled(false);
            current_Balance.setText("00.00");
    
    todayIncome.setText("00.00");
    todayExpense.setText("00.00");
    todayBalance.setText("00.00");
    
    weekIncome.setText("00.00");
    weekExpense.setText("00.00");
    weekBalance.setText("00.00");
    
    monthIncome.setText("00.00");
    monthExpense.setText("00.00");
    monthBalance.setText("00.00");
    
    yearIncome.setText("00.00");
    yearExpense.setText("00.00");
    yearBalance.setText("00.00");
             
        }
        else 
        {
        Login l = new Login();
        this.setVisible(false);
        l.setVisible(true);
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_Login_buttonActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    private void Signup_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Signup_buttonActionPerformed
            String src = evt.getActionCommand();
            System.out.println(src);
        if(src.equals(s.name))
        {
            
            Profile p = new Profile();
            this.setVisible(false);
            p.setVisible(true);
             }
            else
            {
                
                SignUp u = new SignUp();    
            this.setVisible(false);
            u.setVisible(true);
       
            }
    }//GEN-LAST:event_Signup_buttonActionPerformed

    private void Add_ExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_ExpenseActionPerformed
        Add_Expense e = new Add_Expense();
        this.setVisible(false);
        e.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_Add_ExpenseActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_page().setVisible(true);
            }
        });
    }

    private static class Login_button {

        private static void setText(String login) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public Login_button() {
        }
    }

    private static class Signup_button {

        private static void setText(String sign_Up) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public Signup_button() {
        }
    }

}
