
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vaibhav
 */
public class Summary extends javax.swing.JFrame {
    
        Connection connect = null;
        Statement stmt=null;
        session s = new session();
        DefaultTableModel dm;
        DefaultTableModel wm;
        DefaultTableModel mm;
        DefaultTableModel ym;
        

    /**
     * Creates new form summary
     */
    public Summary() {
        initComponents();
           Color c = new Color(204,255,204);
        getContentPane().setBackground(c);
        connect = connectDB.connDB();  
        
     this.setBalance();
     this.setDates();
     this.setTable();
     this.getaTableData();
     this.getwTableData();
     this.getmTableData();
     this.getyTableData();
     
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        weekly = new javax.swing.JTabbedPane();
        jPanel12 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        alledate = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        totalInc = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        totalExp = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        totalBal = new javax.swing.JLabel();
        allsdate = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        atable = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        weekIncome = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        weekExpense = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        weekBalance = new javax.swing.JLabel();
        weeksdate = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        weekedate = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        wtable = new javax.swing.JTable();
        jPanel14 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        monthIncome = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        monthExpense = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        monthBalance = new javax.swing.JLabel();
        monthsdate = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        monthedate = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        mtable = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        yearIncome = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        yearExpense = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        yearBalance = new javax.swing.JLabel();
        yearsdate = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        yearedate = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ytable = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Expense Manager");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        weekly.setPreferredSize(new java.awt.Dimension(700, 500));

        jPanel12.setBackground(new java.awt.Color(204, 255, 204));

        jLabel28.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel28.setText("From Date");

        alledate.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        alledate.setText("Date");

        jPanel13.setBackground(new java.awt.Color(204, 255, 204));

        jLabel30.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel30.setText("Income");

        totalInc.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        totalInc.setText("10000");

        jLabel31.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel31.setText("Expense");

        totalExp.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        totalExp.setText("20000");

        jLabel32.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel32.setText("Balance");

        totalBal.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        totalBal.setText("3000");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(totalInc))
                .addGap(287, 287, 287)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(totalExp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(totalBal)))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalInc)
                            .addComponent(totalExp)))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalBal)))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        allsdate.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        allsdate.setText("Date");

        jLabel40.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel40.setText("To Date");

        atable.setAutoCreateRowSorter(true);
        atable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        atable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        atable.setName(""); // NOI18N
        atable.setSelectionBackground(new java.awt.Color(204, 255, 204));
        atable.setShowHorizontalLines(false);
        atable.setSurrendersFocusOnKeystroke(true);
        jScrollPane1.setViewportView(atable);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(18, 18, 18)
                        .addComponent(allsdate)
                        .addGap(132, 132, 132)
                        .addComponent(jLabel40)
                        .addGap(32, 32, 32)
                        .addComponent(alledate)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(alledate)
                    .addComponent(allsdate)
                    .addComponent(jLabel40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 303, Short.MAX_VALUE)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addGap(60, 60, 60)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(80, Short.MAX_VALUE)))
        );

        weekly.addTab("All", jPanel12);

        jPanel8.setBackground(new java.awt.Color(204, 255, 204));

        jLabel19.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel19.setText("From Date");

        jPanel10.setBackground(new java.awt.Color(204, 255, 204));

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel12.setText("Income");

        weekIncome.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        weekIncome.setText("10000");

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel13.setText("Expense");

        weekExpense.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        weekExpense.setText("20000");

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel14.setText("Balance");

        weekBalance.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        weekBalance.setText("3000");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(weekIncome))
                .addGap(287, 287, 287)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(weekExpense))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(weekBalance)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(weekIncome)
                            .addComponent(weekExpense)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(weekBalance)))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        weeksdate.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        weeksdate.setText("Date");

        jLabel41.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel41.setText("To Date");

        weekedate.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        weekedate.setText("Date");

        wtable.setAutoCreateRowSorter(true);
        wtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        wtable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        wtable.setName(""); // NOI18N
        wtable.setSelectionBackground(new java.awt.Color(204, 255, 204));
        wtable.setSurrendersFocusOnKeystroke(true);
        jScrollPane2.setViewportView(wtable);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(weeksdate)
                        .addGap(132, 132, 132)
                        .addComponent(jLabel41)
                        .addGap(32, 32, 32)
                        .addComponent(weekedate)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(weekedate)
                        .addComponent(weeksdate)
                        .addComponent(jLabel41)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        weekly.addTab("Weekly", jPanel8);

        jPanel14.setBackground(new java.awt.Color(204, 255, 204));

        jLabel34.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel34.setText("From Date");

        jPanel15.setBackground(new java.awt.Color(204, 255, 204));

        jLabel36.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel36.setText("Income");

        monthIncome.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        monthIncome.setText("10000");

        jLabel37.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel37.setText("Expense");

        monthExpense.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        monthExpense.setText("20000");

        jLabel38.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel38.setText("Balance");

        monthBalance.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        monthBalance.setText("3000");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addComponent(monthIncome))
                .addGap(287, 287, 287)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addComponent(monthExpense))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(monthBalance)))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel36)
                            .addComponent(jLabel37))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(monthIncome)
                            .addComponent(monthExpense)))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(monthBalance)))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        monthsdate.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        monthsdate.setText("Date");

        jLabel42.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel42.setText("To Date");

        monthedate.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        monthedate.setText("Date");

        mtable.setAutoCreateRowSorter(true);
        mtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        mtable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mtable.setName(""); // NOI18N
        mtable.setSelectionBackground(new java.awt.Color(204, 255, 204));
        mtable.setSurrendersFocusOnKeystroke(true);
        jScrollPane3.setViewportView(mtable);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addGap(18, 18, 18)
                        .addComponent(monthsdate)
                        .addGap(132, 132, 132)
                        .addComponent(jLabel42)
                        .addGap(32, 32, 32)
                        .addComponent(monthedate)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(monthedate)
                        .addComponent(monthsdate)
                        .addComponent(jLabel42)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        weekly.addTab("Monthly", jPanel14);

        jPanel9.setBackground(new java.awt.Color(204, 255, 204));

        jLabel22.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel22.setText("From Date");

        jPanel11.setBackground(new java.awt.Color(204, 255, 204));

        jLabel24.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel24.setText("Income");

        yearIncome.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        yearIncome.setText("10000");

        jLabel25.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel25.setText("Expense");

        yearExpense.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        yearExpense.setText("20000");

        jLabel26.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel26.setText("Balance");

        yearBalance.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        yearBalance.setText("3000");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(yearIncome))
                .addGap(287, 287, 287)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(yearExpense))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(yearBalance)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yearIncome)
                            .addComponent(yearExpense)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yearBalance)))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        yearsdate.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        yearsdate.setText("Date");

        jLabel43.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel43.setText("To Date");

        yearedate.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        yearedate.setText("Date");

        ytable.setAutoCreateRowSorter(true);
        ytable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ytable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ytable.setName(""); // NOI18N
        ytable.setSelectionBackground(new java.awt.Color(204, 255, 204));
        ytable.setSurrendersFocusOnKeystroke(true);
        jScrollPane4.setViewportView(ytable);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(yearsdate)
                        .addGap(132, 132, 132)
                        .addComponent(jLabel43)
                        .addGap(32, 32, 32)
                        .addComponent(yearedate)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(yearedate)
                        .addComponent(yearsdate)
                        .addComponent(jLabel43)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 303, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(70, Short.MAX_VALUE)))
        );

        weekly.addTab("Yearly", jPanel9);

        jButton6.setBackground(new java.awt.Color(204, 255, 204));
        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(204, 255, 204));
        jButton7.setText("Edit Expense");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(weekly, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addGap(18, 18, 18)
                .addComponent(weekly, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void getaTableData()
    {
        try {                              
                    String sql = "select * from expense_report where user = \'"+s.id+"\' order by Date desc ";
                    stmt = connect.createStatement();
                                            
                    ResultSet rse=stmt.executeQuery(sql);
                    while (rse.next()) {  
                                        java.util.Date d = rse.getDate("Date");
                                            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-YY");
                                            String dd= sdf.format(d);
                                            int t = rse.getInt("Type");
                                            String type="";
                                            if(t==0)
                                            {
                                                 type = "Income"; 
                                            }
                                            else
                                            {
                                              type = "Expense";  
                                            }
                                            int amt = rse.getInt("Amount");
                                            int ide = rse.getInt("ID");
                                            String ides = Integer.toString(ide);
                                            
                                            String amount = Integer.toString(amt);
                                            String cat = rse.getString("Category");
                                            String subcat = rse.getString("SubCategory");
                                            String paymet = rse.getString("PaymentMethod");
                                            String status = rse.getString("Status");
                                            
                                            Vector<String> vector = new Vector<String>();  
                                             vector.add(ides);  

                                             vector.add(dd);  
                                             vector.add(type);  
                                             vector.add(amount);  
                                             vector.add(cat);  
                                             vector.add(subcat);  
                                             vector.add(paymet);  
                                             vector.add(status);  
                                             dm.addRow(vector);             
                                                                     }
        } catch (SQLException e) {
                                                        JOptionPane.showMessageDialog(null, e);
                                                    }
    }
    
    private void getwTableData()
    {
        try {                              
                    String sql = "select * from expense_report where user = \'"+s.id+"\' AND Date between date_sub(now(),INTERVAL DAYOFWEEK(NOW())-2 DAY) and now() order by Date desc ";
                    stmt = connect.createStatement();
                                            
                    ResultSet rse=stmt.executeQuery(sql);
                    while (rse.next()) {  
                                        java.util.Date d = rse.getDate("Date");
                                            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-YY");
                                            String dd= sdf.format(d);
                                            int t = rse.getInt("Type");
                                            String type="";
                                            if(t==0)
                                            {
                                                 type = "Income"; 
                                            }
                                            else
                                            {
                                              type = "Expense";  
                                            }
                                            int amt = rse.getInt("Amount");
                                            int ide = rse.getInt("ID");
                                            String ides = Integer.toString(ide);
                                            
                                            String amount = Integer.toString(amt);
                                            String cat = rse.getString("Category");
                                            String subcat = rse.getString("SubCategory");
                                            String paymet = rse.getString("PaymentMethod");
                                            String status = rse.getString("Status");
                                            
                                            Vector<String> vector = new Vector<String>();  
                                             vector.add(ides);  

                                             vector.add(dd);  
                                             vector.add(type);  
                                             vector.add(amount);  
                                             vector.add(cat);  
                                             vector.add(subcat);  
                                             vector.add(paymet);  
                                             vector.add(status);  
                                             wm.addRow(vector);             
                                                                     }
        } catch (SQLException e) {
                                                        JOptionPane.showMessageDialog(null, e);
                                                    }
    }
    
    private void getmTableData()
    {
        try {                              
                    String sql = "select * from expense_report where user = \'"+s.id+"\' AND Date between date_sub(now(),INTERVAL DAYOFMONTH(NOW())-1 DAY) and now() order by Date desc ";
                    stmt = connect.createStatement();
                                            
                    ResultSet rse=stmt.executeQuery(sql);
                    while (rse.next()) {  
                                        java.util.Date d = rse.getDate("Date");
                                            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-YY");
                                            String dd= sdf.format(d);
                                            int t = rse.getInt("Type");
                                            String type="";
                                            if(t==0)
                                            {
                                                 type = "Income"; 
                                            }
                                            else
                                            {
                                              type = "Expense";  
                                            }
                                            int amt = rse.getInt("Amount");
                                            int ide = rse.getInt("ID");
                                            String ides = Integer.toString(ide);
                                            
                                            String amount = Integer.toString(amt);
                                            String cat = rse.getString("Category");
                                            String subcat = rse.getString("SubCategory");
                                            String paymet = rse.getString("PaymentMethod");
                                            String status = rse.getString("Status");
                                            
                                            Vector<String> vector = new Vector<String>();  
                                             vector.add(ides);  
                                             vector.add(dd);  
                                             vector.add(type);  
                                             vector.add(amount);  
                                             vector.add(cat);  
                                             vector.add(subcat);  
                                             vector.add(paymet);  
                                             vector.add(status);  
                                             mm.addRow(vector);             
                                                                     }
        } catch (SQLException e) {
                                                        JOptionPane.showMessageDialog(null, e);
                                                    }
    }
    
    private void getyTableData()
    {
        try {                              
                    String sql = "select * from expense_report where user = \'"+s.id+"\' AND Date between date_sub(now(),INTERVAL DAYOFYEAR(NOW())-1 DAY) and now() order by Date desc ";
                    stmt = connect.createStatement();
                                            
                    ResultSet rse=stmt.executeQuery(sql);
                    while (rse.next()) {  
                                        java.util.Date d = rse.getDate("Date");
                                            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-YY");
                                            String dd= sdf.format(d);
                                            
                                            int t = rse.getInt("Type");
                                            String type="";
                                            if(t==0)
                                            {
                                                 type = "Income"; 
                                            }
                                            else
                                            {
                                              type = "Expense";  
                                            }
                                            int amt = rse.getInt("Amount");
                                            String amount = Integer.toString(amt);
                                            int ide = rse.getInt("ID");
                                            String ides = Integer.toString(ide);
                                            String cat = rse.getString("Category");
                                            String subcat = rse.getString("SubCategory");
                                            String paymet = rse.getString("PaymentMethod");
                                            String status = rse.getString("Status");
                                            
                                            Vector<String> vector = new Vector<String>();  

                                             vector.add(ides);  
                                             vector.add(dd);  
                                             vector.add(type);  
                                             vector.add(amount);
                                             vector.add(cat);  
                                             vector.add(subcat);  
                                             vector.add(paymet);  
                                             vector.add(status);  
                                             ym.addRow(vector);             
                                                                     }
        } catch (SQLException e) {
                                                        JOptionPane.showMessageDialog(null, e);
                                                    }
    }
    private void setTable() {  
     dm = new DefaultTableModel(0, 0);  
     String s[] = new String[]{"ID", "Date", "Type", "Amount" ,"Category" ,"Sub Category" ,"Payment Method" ,"Status"};  
     dm.setColumnIdentifiers(s);  
     
     wm = new DefaultTableModel(0, 0);  
     wm.setColumnIdentifiers(s);  
     
     mm = new DefaultTableModel(0, 0);  
     mm.setColumnIdentifiers(s);  
     
     ym = new DefaultTableModel(0, 0);  
     ym.setColumnIdentifiers(s);  
     
     atable.setModel(dm);
     wtable.setModel(wm);
     mtable.setModel(mm);
     ytable.setModel(ym);
     
   }  
    private void setDates()
    {
       java.util.Date lastd = Calendar.getInstance().getTime();
         try {                              
                    String sqle = "select Date from expense_report where user = \'"+s.id+"\' order by Date asc ";
                    stmt = connect.createStatement();
                                            
                    ResultSet rse=stmt.executeQuery(sqle);
                                            
				if(rse.next())
                                {
                                    lastd = rse.getDate(1);
                                }    
                                
                                 } catch (SQLException e) {
                                                        JOptionPane.showMessageDialog(null, e);
                                                    }
        java.util.Date d = Calendar.getInstance().getTime();
        Calendar week = Calendar.getInstance(); 
        week.set(Calendar.DAY_OF_WEEK, 2);
        java.util.Date wd = week.getTime();
        
        Calendar month = Calendar.getInstance(); 
        month.set(Calendar.DAY_OF_MONTH, 1);
        java.util.Date md = month.getTime();
        
        Calendar year = Calendar.getInstance(); 
        year.set(Calendar.DAY_OF_YEAR, 1);
        java.util.Date yd = year.getTime();
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd - MM - YYYY");
        
        String lastDate = sdf.format(lastd);
        String curDate = sdf.format(d);
        String curWeeke = sdf.format(d);
        String curWeeks = sdf.format(wd);
        String curMonths = sdf.format(md);
        String curMonthe = sdf.format(d);
        String curYears = sdf.format(yd);
        String curYeare= sdf.format(d);
        allsdate.setText(lastDate);
        alledate.setText(curDate);
        weeksdate.setText(curWeeks);
        weekedate.setText(curWeeke);
        monthsdate.setText(curMonths);
        monthedate.setText(curMonthe);
        yearsdate.setText(curYears);
        yearedate.setText(curYeare);
        
        
    }

 private void setBalance()
    {
                                        int totalIncome =0;
                                        int tIncome =0;
                                        int tExpense =0;
                                        int wIncome =0;
                                        int wExpense =0;
                                        int mIncome =0;
                                        int mExpense =0;
                                        int yIncome =0;
                                        int yExpense =0;
                                        int tbalance = 0;
                                        int wbalance = 0;
                                        int mbalance = 0;
                                        int ybalance = 0;
                                        int totalExpense = 0;  
                                        int totalBalance = 0;
        
        try {                              
                    String sqle = "select SUM(Amount) from expense_report where user = \'"+s.id+"\' AND  Type = 1 ";
                    String sqli = "select SUM(Amount) from expense_report where user = \'"+s.id+"\' AND  Type = 0 ";
                    String sqlti = "select SUM(Amount) from expense_report where user = \'"+s.id+"\' AND  Type = 0 AND Date = curdate()";
                    String sqlte = "select SUM(Amount) from expense_report where user = \'"+s.id+"\' AND  Type = 1 AND Date = curdate()";
                    String sqlwi = "select SUM(Amount) from expense_report where user = \'"+s.id+"\' AND  Type = 0 AND Date between date_sub(now(),INTERVAL DAYOFWEEK(NOW())-2 DAY) and now()";
                    String sqlwe = "select SUM(Amount) from expense_report where user = \'"+s.id+"\' AND  Type = 1 AND Date between date_sub(now(),INTERVAL DAYOFWEEK(NOW())-2 DAY) and now()";
                    String sqlme = "select SUM(Amount) from expense_report where user = \'"+s.id+"\' AND  Type = 1 AND Date between date_sub(now(),INTERVAL DAYOFMONTH(NOW())-1 DAY) and now()";
                    String sqlmi = "select SUM(Amount) from expense_report where user = \'"+s.id+"\' AND  Type = 0 AND Date between date_sub(now(),INTERVAL DAYOFMONTH(NOW())-1 DAY) and now()";
                    String sqlye = "select SUM(Amount) from expense_report where user = \'"+s.id+"\' AND  Type = 1 AND Date between date_sub(now(),INTERVAL DAYOFYEAR(NOW())-1 DAY) and now()";
                    String sqlyi = "select SUM(Amount) from expense_report where user = \'"+s.id+"\' AND  Type = 0 AND Date between date_sub(now(),INTERVAL DAYOFYEAR(NOW())-1 DAY) and now()";
                                                                    
                    stmt = connect.createStatement();
                                            ResultSet rse=stmt.executeQuery(sqle);
                                            
				while(rse.next())
				{
                                    int e = rse.getInt(1);
                                     totalExpense += e;
                                }
                                ResultSet rsi=stmt.executeQuery(sqli);
                                
                                while(rsi.next())
				{
                                     int i = rsi.getInt(1);
                                     totalIncome += i;
                                }
                                
                                ResultSet rsti=stmt.executeQuery(sqlti);
                                
                                while(rsti.next())
				{
                                     int ti = rsti.getInt(1);
                                     tIncome += ti;
                                }
                                
                                ResultSet rste=stmt.executeQuery(sqlte);
                                
                                while(rste.next())
				{
                                     int te = rste.getInt(1);
                                     tExpense += te;
                                }
                                
                                ResultSet rswi=stmt.executeQuery(sqlwi);
                                
                                while(rswi.next())
				{
                                     int wi = rswi.getInt(1);
                                     wIncome += wi;
                                }
                                
                                ResultSet rswe=stmt.executeQuery(sqlwe);
                                
                                while(rswe.next())
				{
                                     int we = rswe.getInt(1);
                                     wExpense += we;
                                }
                                
                                ResultSet rsmi=stmt.executeQuery(sqlmi);
                                
                                while(rsmi.next())
				{
                                     int mi = rsmi.getInt(1);
                                     mIncome += mi;
                                }
                                
                                ResultSet rsme=stmt.executeQuery(sqlme);
                                
                                while(rsme.next())
				{
                                     int me = rsme.getInt(1);
                                     mExpense += me;
                                }
                                
                                ResultSet rsyi=stmt.executeQuery(sqlyi);
                                
                                while(rsyi.next())
				{
                                     int yi = rsyi.getInt(1);
                                     yIncome += yi;
                                }
                                
                                ResultSet rsye=stmt.executeQuery(sqlye);
                                
                                while(rsye.next())
				{
                                     int ye = rsye.getInt(1);
                                     yExpense += ye;
                                }
                                              } catch (SQLException e) {
                                                        JOptionPane.showMessageDialog(null, e);
                                                    }
        
    
    totalBalance = totalIncome- totalExpense;
    wbalance = wIncome- wExpense;
    mbalance = mIncome- mExpense;
    ybalance = yIncome- yExpense;
    
    totalBal.setText(Integer.toString(totalBalance));
    totalInc.setText(Integer.toString(totalIncome));
    totalExp.setText(Integer.toString(totalExpense));
        
    weekIncome.setText(Integer.toString(wIncome));
    weekExpense.setText(Integer.toString(wExpense));
    weekBalance.setText(Integer.toString(wbalance));
    
    monthIncome.setText(Integer.toString(mIncome));
    monthExpense.setText(Integer.toString(mExpense));
    monthBalance.setText(Integer.toString(mbalance));
    
    yearIncome.setText(Integer.toString(yIncome));
    yearExpense.setText(Integer.toString(yExpense));
    yearBalance.setText(Integer.toString(ybalance));
    
    }    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed


        Main_page e = new Main_page();
        this.setVisible(false);
        e.setVisible(true);

        

       
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
Edit_Expense e = new Edit_Expense();
this.setVisible(false);
e.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Summary().setVisible(true);
            }
        });
    }
    private javax.swing.JPanel Table;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alledate;
    private javax.swing.JLabel allsdate;
    private javax.swing.JTable atable;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel monthBalance;
    private javax.swing.JLabel monthExpense;
    private javax.swing.JLabel monthIncome;
    private javax.swing.JLabel monthedate;
    private javax.swing.JLabel monthsdate;
    private javax.swing.JTable mtable;
    private javax.swing.JLabel totalBal;
    private javax.swing.JLabel totalExp;
    private javax.swing.JLabel totalInc;
    private javax.swing.JLabel weekBalance;
    private javax.swing.JLabel weekExpense;
    private javax.swing.JLabel weekIncome;
    private javax.swing.JLabel weekedate;
    private javax.swing.JTabbedPane weekly;
    private javax.swing.JLabel weeksdate;
    private javax.swing.JTable wtable;
    private javax.swing.JLabel yearBalance;
    private javax.swing.JLabel yearExpense;
    private javax.swing.JLabel yearIncome;
    private javax.swing.JLabel yearedate;
    private javax.swing.JLabel yearsdate;
    private javax.swing.JTable ytable;
    // End of variables declaration//GEN-END:variables
}
